### ISSUE TITLE
Maxlenght

### ISSUE THREAD

**Issue by dhyogo** [codermarcos/simple-mask-money#23]
Hi! Is it possible to use the maxlenght property?

**Comment by codermarcos** [comment]
Many thanks for your issue is very important to help improve our package. 😄 👍 
No, at this time it is not possible to define formatting or conditions in values, but this is an excellent idea and can enter the roadmap,  however see a more generic implementation than just max length. 
In version [3](https://github.com/codermarcos/simple-mask-money/releases/tag/v3.0.0) we have [2 callback](https://github.com/codermarcos/simple-mask-money/tree/master/docs/3.x.x#simplemaskmoneyargs) methods **beforFormat** and **afterFormat** I believe we can implement a way to return a value in this callback that will set the new input value so that you have the freedom to implement what you need. Anyway this will be included in the next versions if you want to contribute more feel free to send your a pull request... Thanks :heart:
