### ISSUE TITLE
.formatToNumber is not working correctly

### ISSUE THREAD

**Issue by mkydouglas** [codermarcos/simple-mask-money#24]
Hey guys, "SimpleMaskMoney.formatToNumber(this.val)" is returning a value with a dot, and I need the value as a number. Could you help me? I'm attaching a image showing the return.
Thanks!!

![71266797-e885c900-2327-11ea-864e-5a473ea8043f](https://user-images.githubusercontent.com/40704841/71266979-47e3d900-2328-11ea-903e-0c120fabd240.png)

**Comment by codermarcos** [comment]
Many thanks for your issue is very important to help improve our package. :smile: :+1: 
This is expected behavior because this method returns the value in the default number format. Anyway we can think of some cool solution to include in the project to solve your problem send a solution idea to include in the next versions or if you want to contribute more feel free to send your a pull request... Tks :heart:
