### ISSUE TITLE
How to remove completly remove input value?

### ISSUE THREAD

**Issue by EduFrazao** [codermarcos/simple-mask-money#39]
Its possible to remove all values of this field, leaving it blank. So the user can specify if he wants to set this field as null, or if it is really a zero value?

**Comment by codermarcos** [comment]
Many thanks for your issue is very important to help improve our package. :smile: :+1:
Today no but we have the idea to recreate **simple-mask-money** with typescript native, improving performance and others idéas...We will be immensely happy that more people contribute to the project, feel free to open a pull request including this or do some refactoring Tks :heart:
